CREATE SCHEMA IF NOT EXISTS rsvp;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS rsvp.invites (
    "id" uuid default uuid_generate_v4() PRIMARY KEY,
    "invited_to" text not null,
    "created_at" timestamp not null,
    "updated_at" timestamp
);

CREATE TABLE IF NOT EXISTS rsvp.users (
    "id" uuid default uuid_generate_v4() PRIMARY KEY,
    "first_name" text not null,
    "last_name" text not null,
    "invite_id" uuid not null references rsvp.invites on delete cascade,
    "user_id" uuid references auth.users on delete cascade,
    "is_coming" boolean,
    "created_at" timestamp not null
);

CREATE TABLE IF NOT EXISTS rsvp.responses (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    "rsvp_user_id" uuid not null references rsvp.users on delete cascade,
    "is_vegan" boolean,
    "is_vegetarian" boolean,
    "no_gluten" boolean,
    "no_nuts" boolean,
    "no_dairy" boolean,
    "other" text,
    "created_at" timestamp
);
